# Generated by Django 4.2.5 on 2024-01-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0007_drop_nav_items_navbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_nav',
            name='link',
        ),
        migrations.RemoveField(
            model_name='basic_nav',
            name='title',
        ),
        migrations.AddField(
            model_name='basic_nav',
            name='link_after',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basic_nav',
            name='link_before',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='basic_nav',
            name='title_after',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='basic_nav',
            name='title_before',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
