# Generated by Django 4.2.5 on 2024-01-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0008_remove_basic_nav_link_remove_basic_nav_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic_nav',
            old_name='link_after',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='basic_nav',
            old_name='title_after',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='basic_nav',
            name='link_before',
        ),
        migrations.RemoveField(
            model_name='basic_nav',
            name='title_before',
        ),
    ]
