# Generated by Django 4.2.5 on 2024-01-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0010_nav_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav_image',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
