# Generated by Django 4.2.5 on 2024-01-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0011_alter_nav_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav_image',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='navlogo'),
        ),
        migrations.AlterField(
            model_name='nav_image',
            name='title',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='nav_image',
            name='title_image',
            field=models.ImageField(default=None, null=True, upload_to='navlogo'),
        ),
    ]
