# Generated by Django 4.2.5 on 2024-01-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0020_slider_link_slider_refer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(),
        ),
    ]
