# Generated by Django 4.2.5 on 2024-01-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0023_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a1_top_header_right',
            name='Link',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
