# Generated by Django 4.2.5 on 2024-01-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0028_rename_link_a3_navbar_deepdropdown_links_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='A3_NAVBAR_MAIN_LINKS_AFTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='a3_navbar_dropdown_links',
            name='main_nav',
        ),
    ]
