# Generated by Django 4.2.5 on 2024-01-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0032_alter_a3_navbar_deepdropdown_links_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A3_DeepDropdownMenu',
        ),
    ]
