# Generated by Django 4.2.5 on 2024-01-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0037_a2maindropnav_a2mainnav_a2mainnavafter_a2navlogo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='A3TOPSLIDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Slider')),
                ('Title', models.CharField(max_length=100)),
                ('Text', models.TextField()),
                ('Button', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='a2navlogo',
            name='Image',
            field=models.ImageField(null=True, upload_to='Nav Logo'),
        ),
    ]
