# Generated by Django 4.2.5 on 2024-01-29 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0039_a4bottomslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='A3TOPFEATURED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Text', models.TextField()),
                ('Image', models.ImageField(null=True, upload_to='Top Featured')),
                ('Time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='A3TOPSLIDER',
        ),
        migrations.DeleteModel(
            name='A4BOTTOMSLIDER',
        ),
    ]
