# Generated by Django 4.2.5 on 2024-01-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0042_a5newpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='A5TOPSTORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Image', models.ImageField(upload_to='Top Story')),
            ],
        ),
        migrations.DeleteModel(
            name='A5NEWPOST',
        ),
    ]
