# Generated by Django 4.2.5 on 2024-01-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0047_alter_a9whatsnewnav_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='A10OLDOTHERTRENDINGTOPSTORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Text', models.TextField()),
                ('Image', models.ImageField(upload_to='Old Other Trending Top Story')),
            ],
        ),
        migrations.CreateModel(
            name='A9OTHERTRENDINGSTORIES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Image', models.ImageField(upload_to='Other Stories')),
                ('Text', models.TextField()),
                ('Describetion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='A9WHATSNEWNAV',
        ),
    ]
