# Generated by Django 4.2.5 on 2024-01-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0048_a10oldothertrendingtopstory_a9othertrendingstories_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A10OLDOTHERTRENDINGTOPSTORY',
            new_name='B1OLDOTHERTRENDINGTOPSTORY',
        ),
    ]
