# Generated by Django 4.2.5 on 2024-01-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0051_b2mostviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='B3OTHERNEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('Image', models.ImageField(upload_to='Other News')),
            ],
        ),
    ]
