# Generated by Django 4.2.5 on 2024-02-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0055_b8imagegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='A1TOPDROPLEFTNAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, null=True)),
                ('Link', models.URLField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='a1topleftnav',
            name='Link',
        ),
    ]
