# Generated by Django 4.2.5 on 2024-02-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0061_b9subscribenews_delete_b9subscibenews'),
    ]

    operations = [
        migrations.AddField(
            model_name='b9subscribenews',
            name='Image',
            field=models.ImageField(null=True, upload_to='Subscribe News'),
        ),
        migrations.AddField(
            model_name='b9subscribenews',
            name='Subtitle',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
