# Generated by Django 4.2.5 on 2024-02-04 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0062_b9subscribenews_image_b9subscribenews_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='a8latestnews',
            name='Source',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='a8latestnews',
            name='Time',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
