# Generated by Django 4.2.5 on 2024-02-04 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0064_b1oldothertrendingtopstory_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2mostviews',
            name='Source',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='b2mostviews',
            name='Time',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='b3othernews',
            name='Source',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='b3othernews',
            name='Time',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='b4popularnews',
            name='Time',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='b6storeads',
            name='Button',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
