# Generated by Django 4.2.5 on 2024-02-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0065_b2mostviews_source_b2mostviews_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b3othernews',
            old_name='Text',
            new_name='Title',
        ),
    ]
