# Generated by Django 4.2.5 on 2024-02-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0069_remove_a4newpost_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='B9SUBSCRIBENEWS',
            new_name='A7SUBSCRIBENEWS',
        ),
        migrations.DeleteModel(
            name='A7OLDTRENDINGTOPSTORY',
        ),
    ]
