# Generated by Django 4.2.5 on 2024-02-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0074_a3topfeatured_head_a4newpost_head'),
    ]

    operations = [
        migrations.DeleteModel(
            name='B4POPULARNEWS',
        ),
        migrations.DeleteModel(
            name='B5TRENDINGTAGS',
        ),
        migrations.AddField(
            model_name='b6storeads',
            name='Link',
            field=models.URLField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='b6storeads',
            name='Image',
            field=models.ImageField(upload_to='Ads'),
        ),
    ]
