# Generated by Django 4.2.5 on 2024-02-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0092_a6othernews'),
    ]

    operations = [
        migrations.AddField(
            model_name='a6othernews',
            name='Source',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
