# Generated by Django 4.2.5 on 2024-02-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0095_a7ecoandworld'),
    ]

    operations = [
        migrations.AddField(
            model_name='a7ecoandworld',
            name='Text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
