# Generated by Django 4.2.5 on 2024-02-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0097_a8lifestyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='A9BOTTOMNAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, null=True)),
                ('Link', models.URLField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='B1OURORIGINAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Original Gallery')),
            ],
        ),
    ]
