# Generated by Django 4.2.5 on 2024-02-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0099_b2storeads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b2storeads',
            name='Text',
        ),
    ]
