# Generated by Django 4.2.5 on 2024-02-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0103_rename_business_b3website_tags_ecoandworld_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='B4HORIZONTABANNER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Horizontal Ads')),
            ],
        ),
        migrations.AddField(
            model_name='a2toppicks',
            name='Source',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
