# Generated by Django 4.2.5 on 2024-01-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagetitlelogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotitle', models.ImageField(upload_to='titlelogo')),
            ],
        ),
    ]
