# Generated by Django 4.2.5 on 2024-01-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0012_alter_nav_image_image_alter_nav_image_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nav_image',
            name='title_image',
        ),
        migrations.AlterField(
            model_name='nav_image',
            name='image',
            field=models.ImageField(default=None, upload_to='navlogo'),
        ),
    ]
