# Generated by Django 4.2.5 on 2024-01-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0013_remove_nav_image_title_image_alter_nav_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav_image',
            name='link',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
