# Generated by Django 4.2.5 on 2024-01-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0021_alter_slider_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='basic_nav',
        ),
        migrations.RemoveField(
            model_name='drop_nav_items',
            name='navbar',
        ),
        migrations.DeleteModel(
            name='nav_image',
        ),
        migrations.DeleteModel(
            name='nav_title',
        ),
        migrations.DeleteModel(
            name='Pagetitle',
        ),
        migrations.DeleteModel(
            name='Pagetitlelogo',
        ),
        migrations.DeleteModel(
            name='slider',
        ),
        migrations.DeleteModel(
            name='drop_nav',
        ),
        migrations.DeleteModel(
            name='drop_nav_items',
        ),
    ]
