# Generated by Django 4.2.5 on 2024-01-19 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0029_a3_navbar_main_links_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='A3_DeepDropdownMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Link', models.URLField()),
                ('dropdown_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deep_dropdown_menus', to='xyolace_app.a3_navbar_deepdropdown_links')),
            ],
        ),
    ]
