# Generated by Django 4.2.5 on 2024-01-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0033_delete_a3_deepdropdownmenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A0_PAGE_LOGO',
        ),
        migrations.DeleteModel(
            name='A0_PAGE_TITLE',
        ),
        migrations.DeleteModel(
            name='A1_TOP_HEADER_RIGHT',
        ),
        migrations.DeleteModel(
            name='A2_NAVBAR_IMAGE',
        ),
        migrations.DeleteModel(
            name='A2_NAVBAR_TITLE',
        ),
        migrations.RemoveField(
            model_name='a3_navbar_deepdropdown_links',
            name='dropdown_menu',
        ),
        migrations.DeleteModel(
            name='A3_NAVBAR_MAIN_LINKS',
        ),
        migrations.DeleteModel(
            name='A3_NAVBAR_MAIN_LINKS_AFTER',
        ),
        migrations.DeleteModel(
            name='A3_NAVBAR_DEEPDROPDOWN_LINKS',
        ),
        migrations.DeleteModel(
            name='A3_NAVBAR_DROPDOWN_LINKS',
        ),
    ]
