# Generated by Django 4.2.5 on 2024-01-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0038_a3topslider_alter_a2navlogo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='A4BOTTOMSLIDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Bottom Slider')),
                ('Title', models.CharField(max_length=20)),
                ('Text', models.CharField(max_length=30)),
                ('Price', models.CharField(max_length=30, null=True)),
                ('False_Price', models.CharField(max_length=30, null=True)),
                ('Button', models.CharField(max_length=30)),
            ],
        ),
    ]
