# Generated by Django 4.2.5 on 2024-02-03 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0056_a1topdropleftnav_remove_a1topleftnav_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='a1topdropleftnav',
            name='dropdown_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deep_dropdown_menus', to='xyolace_app.a1topleftnav'),
        ),
    ]
