# Generated by Django 4.2.5 on 2024-02-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0057_a1topdropleftnav_dropdown_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a1topdropleftnav',
            name='dropdown_menu',
        ),
        migrations.DeleteModel(
            name='A1TOPLEFTNAV',
        ),
    ]
