# Generated by Django 4.2.5 on 2024-02-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0068_a4newpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a4newpost',
            name='slug',
        ),
    ]
