# Generated by Django 4.2.5 on 2024-02-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0070_rename_b9subscribenews_a7subscribenews_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A7SUBSCRIBENEWS',
        ),
    ]
