# Generated by Django 4.2.5 on 2024-02-16 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0083_alter_a1navbar_tag_line_alter_a1navbar_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='A2TOP_PICKS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Head', models.CharField(default='Top Picks', max_length=100)),
                ('Field', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=50)),
                ('Text', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Top Featured')),
                ('Time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
