# Generated by Django 4.2.5 on 2024-02-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0084_a2top_picks'),
    ]

    operations = [
        migrations.AddField(
            model_name='a2top_picks',
            name='BGImage',
            field=models.ImageField(blank=True, null=True, upload_to='Top Picks'),
        ),
        migrations.AlterField(
            model_name='a2top_picks',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Top Picks'),
        ),
    ]
