# Generated by Django 4.2.5 on 2024-02-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0086_remove_a2top_picks_bgimage_remove_a2top_picks_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='A3NEWSTODAY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Head', models.CharField(default='Top News Today', max_length=100)),
                ('Title', models.TextField()),
                ('Text', models.TextField()),
                ('Image', models.ImageField(upload_to='New Post')),
            ],
        ),
    ]
