# Generated by Django 4.2.5 on 2024-02-23 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0093_a6othernews_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='a6othernews',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
