# Generated by Django 4.2.5 on 2024-02-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0100_remove_b2storeads_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='B3WEBSITE_TAGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Follow_us_top', models.CharField(max_length=50)),
                ('Hot_Picks', models.CharField(max_length=50)),
                ('Other', models.CharField(max_length=50)),
                ('Business', models.CharField(max_length=50)),
                ('LIFESTYLE', models.CharField(max_length=50)),
                ('Address_head', models.CharField(max_length=50)),
                ('Address_location_head', models.CharField(max_length=50)),
                ('Address_location', models.CharField(max_length=50)),
                ('Address_email_head', models.CharField(max_length=50)),
                ('Address_email', models.CharField(max_length=50)),
                ('Address_Phone_head', models.CharField(max_length=50)),
                ('Address_Phone', models.CharField(max_length=50)),
                ('Twitter_link', models.CharField(max_length=50)),
                ('Facebook_link', models.CharField(max_length=50)),
                ('Youtube_link', models.CharField(max_length=50)),
                ('Instagram_link', models.CharField(max_length=50)),
                ('Recent_head', models.CharField(max_length=50)),
                ('Categories_head', models.CharField(max_length=50)),
                ('Ourgallery_head', models.CharField(max_length=50)),
                ('Site_name', models.CharField(max_length=50)),
                ('Site_head', models.CharField(max_length=50)),
                ('Disclaimer_head', models.CharField(max_length=50)),
                ('Disclaimer_link', models.CharField(max_length=50)),
                ('Email_bar_inside', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='b2storeads',
            name='Title',
            field=models.CharField(max_length=30),
        ),
    ]
