# Generated by Django 4.2.5 on 2024-01-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0002_pagetitlelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DropdownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xyolace_app.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='DeepDropdownItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_dropdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xyolace_app.dropdownitem')),
            ],
        ),
    ]
