# Generated by Django 4.2.5 on 2024-01-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0005_basic_nav_drop_nav_drop_nav_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop_nav_items',
            name='link',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
