# Generated by Django 4.2.5 on 2024-01-14 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0006_drop_nav_items_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop_nav_items',
            name='navbar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xyolace_app.drop_nav'),
        ),
    ]
