# Generated by Django 4.2.5 on 2024-01-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0017_alter_nav_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='nav_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nav_image',
            name='title',
        ),
    ]
