# Generated by Django 4.2.5 on 2024-01-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0019_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='refer_title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
