# Generated by Django 4.2.5 on 2024-01-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0024_a1_top_header_right_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='A2_NAVBAR_IMAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Navbar_Image')),
            ],
        ),
    ]
