# Generated by Django 4.2.5 on 2024-01-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0030_a3_deepdropdownmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a3_deepdropdownmenu',
            name='Link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='a3_deepdropdownmenu',
            name='Title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
