# Generated by Django 4.2.5 on 2024-01-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0031_alter_a3_deepdropdownmenu_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a3_navbar_deepdropdown_links',
            name='Link',
            field=models.URLField(null=True),
        ),
    ]
