# Generated by Django 4.2.5 on 2024-01-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0035_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='A1TOPLEFTNAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, null=True)),
                ('Link', models.URLField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='A1TOPRIGHTNAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, null=True)),
                ('Link', models.URLField(default=None)),
            ],
        ),
    ]
