# Generated by Django 4.2.5 on 2024-01-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0043_a5topstory_delete_a5newpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='A6TRENDINGTOPSTORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Image', models.ImageField(upload_to='Trending Top Story')),
            ],
        ),
        migrations.CreateModel(
            name='A7OLDTRENDINGTOPSTORY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Image', models.ImageField(upload_to='Old Trending Top Story')),
            ],
        ),
    ]
