# Generated by Django 4.2.5 on 2024-01-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0044_a6trendingtopstory_a7oldtrendingtopstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='A8LATESTNEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Image', models.ImageField(upload_to='Old Trending Top Story')),
            ],
        ),
    ]
