# Generated by Django 4.2.5 on 2024-01-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0046_a9whatsnewnav_alter_a8latestnews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a9whatsnewnav',
            name='Tab',
            field=models.CharField(max_length=10),
        ),
    ]
