# Generated by Django 4.2.5 on 2024-01-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0050_rename_describetion_a9othertrendingstories_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2MOSTVIEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Image', models.ImageField(upload_to='Latest News')),
            ],
        ),
    ]
