# Generated by Django 4.2.5 on 2024-01-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0054_b7bottomnav'),
    ]

    operations = [
        migrations.CreateModel(
            name='B8IMAGEGALLERY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Image Gallery')),
            ],
        ),
    ]
