# Generated by Django 4.2.5 on 2024-02-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0059_delete_a1topdropleftnav_delete_a1toprightnav_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='B9SUBSCIBENEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
    ]
