# Generated by Django 4.2.5 on 2024-02-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0067_rename_text_b5trendingtags_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='a4newpost',
            name='slug',
            field=models.SlugField(default=4, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
