# Generated by Django 4.2.5 on 2024-02-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0072_a7subscribenews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A8LATESTNEWS',
        ),
        migrations.DeleteModel(
            name='B1OLDOTHERTRENDINGTOPSTORY',
        ),
    ]
