# Generated by Django 4.2.5 on 2024-02-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0075_delete_b4popularnews_delete_b5trendingtags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='A0PAGETOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Image', models.ImageField(default=None, upload_to='Page Logo')),
            ],
        ),
        migrations.DeleteModel(
            name='A0PAGELOGO',
        ),
        migrations.DeleteModel(
            name='A0PAGETITLE',
        ),
        migrations.DeleteModel(
            name='A3TOPFEATURED',
        ),
        migrations.DeleteModel(
            name='A4NEWPOST',
        ),
        migrations.DeleteModel(
            name='A5TOPSTORY',
        ),
        migrations.DeleteModel(
            name='A6TRENDINGTOPSTORY',
        ),
        migrations.DeleteModel(
            name='A7SUBSCRIBENEWS',
        ),
        migrations.DeleteModel(
            name='A9OTHERTRENDINGSTORIES',
        ),
        migrations.DeleteModel(
            name='B2MOSTVIEWS',
        ),
        migrations.DeleteModel(
            name='B3OTHERNEWS',
        ),
        migrations.DeleteModel(
            name='B6STOREADS',
        ),
        migrations.DeleteModel(
            name='B7BOTTOMNAV',
        ),
        migrations.DeleteModel(
            name='B8IMAGEGALLERY',
        ),
    ]
