# Generated by Django 4.2.5 on 2024-02-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0077_a1navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='a1navbar',
            name='Link_href',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
