# Generated by Django 4.2.5 on 2024-02-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0079_a1navbar_tag_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a1navbar',
            name='Image',
        ),
        migrations.AlterField(
            model_name='a1navbar',
            name='Nav_links',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='a1navbar',
            name='Tag_line',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='a1navbar',
            name='Title',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
