# Generated by Django 4.2.5 on 2024-02-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0081_alter_a1navbar_nav_links_alter_a1navbar_tag_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a1navbar',
            name='Tag_line',
            field=models.CharField(default=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='a1navbar',
            name='Title',
            field=models.CharField(default=True, max_length=30, null=True),
        ),
    ]
