# Generated by Django 4.2.5 on 2024-02-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0087_a3newstoday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A2TOP_PICKS',
            new_name='A2TOPPICKS',
        ),
    ]
