# Generated by Django 4.2.5 on 2024-02-23 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0088_rename_a2top_picks_a2toppicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='A4HOTPICKS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Text', models.TextField()),
                ('Image', models.ImageField(upload_to='Hot Picks')),
                ('Time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='a3newstoday',
            name='Head',
        ),
    ]
