# Generated by Django 4.2.5 on 2024-02-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0090_a5subscribenews'),
    ]

    operations = [
        migrations.AddField(
            model_name='a3newstoday',
            name='Source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='a4hotpicks',
            name='Source',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
