# Generated by Django 4.2.5 on 2024-02-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0091_a3newstoday_source_a4hotpicks_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='A6OTHERNEWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Image', models.ImageField(upload_to='Other News')),
                ('Text', models.TextField()),
                ('Describe', models.TextField()),
            ],
        ),
    ]
