# Generated by Django 4.2.5 on 2024-02-23 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0094_a6othernews_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='A7ECOANDWORLD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Image', models.ImageField(upload_to='Latest News')),
                ('Source', models.CharField(max_length=40, null=True)),
                ('Time', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
