# Generated by Django 4.2.5 on 2024-02-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0102_b3website_tags_latest_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b3website_tags',
            old_name='Business',
            new_name='Ecoandworld',
        ),
        migrations.RenameField(
            model_name='b3website_tags',
            old_name='Site_head',
            new_name='Site_after_name',
        ),
        migrations.AddField(
            model_name='b3website_tags',
            name='Stay_connected',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='b3website_tags',
            name='Address_Phone',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='b3website_tags',
            name='Address_Phone_head',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='b3website_tags',
            name='Facebook_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='b3website_tags',
            name='Instagram_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='b3website_tags',
            name='Twitter_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='b3website_tags',
            name='Youtube_link',
            field=models.URLField(),
        ),
    ]
