# Generated by Django 4.2.5 on 2024-02-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0104_b4horizontabanner_a2toppicks_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='b3website_tags',
            name='Top_Picks',
            field=models.CharField(default='Top Picks', max_length=50),
            preserve_default=False,
        ),
    ]
