# Generated by Django 4.2.5 on 2024-02-26 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0105_b3website_tags_top_picks'),
    ]

    operations = [
        migrations.AddField(
            model_name='a3newstoday',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
