# Generated by Django 4.2.5 on 2024-03-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyolace_app', '0107_b5keywords_des_a2toppicks_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b3website_tags',
            name='Facebook_link',
        ),
        migrations.AddField(
            model_name='a2toppicks',
            name='Source_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='a3newstoday',
            name='Source_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='a4hotpicks',
            name='Source_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='a6othernews',
            name='Source_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='a7ecoandworld',
            name='Source_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='a8lifestyle',
            name='Source_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
